# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x07\x61\x65rosyn\"\xbc\x02\n\x0c\x44roneCommand\x12\x17\n\x0ftarget_drone_id\x18\x01 \x01(\r\x12\x12\n\ncommand_id\x18\x02 \x01(\x03\x12\x16\n\x0eissued_time_us\x18\x03 \x01(\x03\x12\x37\n\x0c\x63ommand_type\x18\x04 \x01(\x0e\x32!.aerosyn.DroneCommand.CommandType\"\xad\x01\n\x0b\x43ommandType\x12\x07\n\x03NOP\x10\x00\x12\x0b\n\x07TAKEOFF\x10\x01\x12\x08\n\x04LAND\x10\x02\x12\x14\n\x10RETURN_TO_LAUNCH\x10\x03\x12\x12\n\x0eRETURN_TO_DOCK\x10\x04\x12\x11\n\rGOTO_POSITION\x10\x05\x12\x11\n\rSUPPRESS_FIRE\x10\x06\x12\x08\n\x04HOLD\x10\x07\x12\n\n\x06RESUME\x10\x08\x12\x18\n\x14SET_BATTERY_OVERRIDE\x10\t\"h\n\x0bGotoCommand\x12\x10\n\x08target_x\x18\x01 \x01(\x02\x12\x10\n\x08target_y\x18\x02 \x01(\x02\x12\x10\n\x08target_z\x18\x03 \x01(\x02\x12\x11\n\tmax_speed\x18\x04 \x01(\x02\x12\x10\n\x08relative\x18\x05 \x01(\x08\"h\n\x12SuppressionCommand\x12\x10\n\x08target_x\x18\x01 \x01(\x02\x12\x10\n\x08target_y\x18\x02 \x01(\x02\x12\x10\n\x08target_z\x18\x03 \x01(\x02\x12\x1c\n\x14suppression_strength\x18\x04 \x01(\x02\"\xbb\x01\n\rConfigCommand\x12-\n\x03key\x18\x01 \x01(\x0e\x32 .aerosyn.ConfigCommand.ConfigKey\x12\r\n\x05value\x18\x02 \x01(\x02\"l\n\tConfigKey\x12\r\n\tDETM_ETA0\x10\x00\x12\x0f\n\x0b\x44\x45TM_LAMBDA\x10\x01\x12\x17\n\x13\x42\x41TTERY_MIN_PERCENT\x10\x02\x12\x0f\n\x0bPAYLOAD_MAX\x10\x03\x12\x15\n\x11\x45NERGY_DRAIN_RATE\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRONECOMMAND._serialized_start=27
  _DRONECOMMAND._serialized_end=343
  _DRONECOMMAND_COMMANDTYPE._serialized_start=170
  _DRONECOMMAND_COMMANDTYPE._serialized_end=343
  _GOTOCOMMAND._serialized_start=345
  _GOTOCOMMAND._serialized_end=449
  _SUPPRESSIONCOMMAND._serialized_start=451
  _SUPPRESSIONCOMMAND._serialized_end=555
  _CONFIGCOMMAND._serialized_start=558
  _CONFIGCOMMAND._serialized_end=745
  _CONFIGCOMMAND_CONFIGKEY._serialized_start=637
  _CONFIGCOMMAND_CONFIGKEY._serialized_end=745
# @@protoc_insertion_point(module_scope)
