# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fire_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ire_data.proto\x12\x07\x61\x65rosyn\"\x84\x01\n\x08\x46ireCell\x12\x0e\n\x06grid_x\x18\x01 \x01(\r\x12\x0e\n\x06grid_y\x18\x02 \x01(\r\x12\x11\n\tintensity\x18\x03 \x01(\x02\x12\x14\n\x0c\x66uel_density\x18\x04 \x01(\x02\x12\x15\n\rtemperature_k\x18\x05 \x01(\x02\x12\x18\n\x10ignition_time_us\x18\x06 \x01(\x03\"\xef\x01\n\x0c\x46ireMapState\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x03\x12\x12\n\ngrid_width\x18\x02 \x01(\r\x12\x13\n\x0bgrid_height\x18\x03 \x01(\r\x12 \n\x05\x63\x65lls\x18\x04 \x03(\x0b\x32\x11.aerosyn.FireCell\x12\x15\n\rwind_speed_ms\x18\x05 \x01(\x02\x12\x1a\n\x12wind_direction_deg\x18\x06 \x01(\x02\x12\x1b\n\x13total_burning_cells\x18\x07 \x01(\r\x12\x15\n\rmax_intensity\x18\x08 \x01(\x02\x12\x17\n\x0fperimeter_cells\x18\t \x01(\r\"\xb2\x01\n\rFireDetection\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\r\x12\x19\n\x11\x64\x65tection_time_us\x18\x02 \x01(\x03\x12\x1c\n\x14\x64\x65tection_confidence\x18\x03 \x01(\x02\x12\x12\n\nposition_x\x18\x04 \x01(\x02\x12\x12\n\nposition_y\x18\x05 \x01(\x02\x12\x12\n\nposition_z\x18\x06 \x01(\x02\x12\x1a\n\x12intensity_estimate\x18\x07 \x01(\x02\"\x98\x01\n\x0f\x46ireSuppression\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\r\x12\x1b\n\x13suppression_time_us\x18\x02 \x01(\x03\x12\x10\n\x08target_x\x18\x03 \x01(\x02\x12\x10\n\x08target_y\x18\x04 \x01(\x02\x12\x1c\n\x14suppression_strength\x18\x05 \x01(\x02\x12\x14\n\x0cpayload_used\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fire_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIRECELL._serialized_start=29
  _FIRECELL._serialized_end=161
  _FIREMAPSTATE._serialized_start=164
  _FIREMAPSTATE._serialized_end=403
  _FIREDETECTION._serialized_start=406
  _FIREDETECTION._serialized_end=584
  _FIRESUPPRESSION._serialized_start=587
  _FIRESUPPRESSION._serialized_end=739
# @@protoc_insertion_point(module_scope)
