# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swarm_telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15swarm_telemetry.proto\x12\x07\x61\x65rosyn\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"0\n\nVector3Vel\x12\n\n\x02vx\x18\x01 \x01(\x02\x12\n\n\x02vy\x18\x02 \x01(\x02\x12\n\n\x02vz\x18\x03 \x01(\x02\"\xc5\x03\n\x0eSwarmTelemetry\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\r\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\x12\"\n\x08position\x18\x03 \x01(\x0b\x32\x10.aerosyn.Vector3\x12%\n\x08velocity\x18\x04 \x01(\x0b\x32\x13.aerosyn.Vector3Vel\x12\x17\n\x0f\x62\x61ttery_percent\x18\x05 \x01(\x02\x12\x19\n\x11payload_remaining\x18\x06 \x01(\r\x12\x17\n\x0f\x66uel_distance_m\x18\x07 \x01(\r\x12\x31\n\x05state\x18\x08 \x01(\x0e\x32\".aerosyn.SwarmTelemetry.DroneState\x12\x15\n\rfire_detected\x18\t \x01(\x08\x12\x16\n\x0e\x66ire_intensity\x18\n \x01(\x02\x12\x10\n\x08rssi_dbm\x18\x0b \x01(\r\x12\x14\n\x0clink_quality\x18\x0c \x01(\x02\"i\n\nDroneState\x12\x08\n\x04IDLE\x10\x00\x12\n\n\x06SEARCH\x10\x01\x12\x0c\n\x08SUPPRESS\x10\x02\x12\x14\n\x10RETURN_TO_LAUNCH\x10\x03\x12\x12\n\x0eRETURN_TO_DOCK\x10\x04\x12\r\n\tFORMATION\x10\x05\"\xd7\x01\n\x15NeighborStateEstimate\x12\x14\n\x0c\x65stimator_id\x18\x01 \x01(\r\x12\x13\n\x0bneighbor_id\x18\x02 \x01(\r\x12,\n\x12\x65stimated_position\x18\x03 \x01(\x0b\x32\x10.aerosyn.Vector3\x12/\n\x12\x65stimated_velocity\x18\x04 \x01(\x0b\x32\x13.aerosyn.Vector3Vel\x12\x17\n\x0f\x65stimate_age_us\x18\x05 \x01(\x03\x12\x1b\n\x13\x65stimate_confidence\x18\x06 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarm_telemetry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3._serialized_start=34
  _VECTOR3._serialized_end=76
  _VECTOR3VEL._serialized_start=78
  _VECTOR3VEL._serialized_end=126
  _SWARMTELEMETRY._serialized_start=129
  _SWARMTELEMETRY._serialized_end=582
  _SWARMTELEMETRY_DRONESTATE._serialized_start=477
  _SWARMTELEMETRY_DRONESTATE._serialized_end=582
  _NEIGHBORSTATEESTIMATE._serialized_start=585
  _NEIGHBORSTATEESTIMATE._serialized_end=800
# @@protoc_insertion_point(module_scope)
